Write-Host "FLL Organizer"
Write-Host "1) Instale Node.js 20+ e PostgreSQL."
Write-Host "2) Crie o arquivo .env baseado em .env.example."
Write-Host "3) Rode:"
Write-Host "   npm install"
Write-Host "   npx prisma generate"
Write-Host "   npx prisma db push"
Write-Host "   npm run db:seed"
Write-Host "   npm run dev"
